networks:
  rossmann-network:
    external: true

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    networks:
      - rossmann-network
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=0.0.0.0
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "1600:7077"
      - "1601:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    networks:
      - rossmann-network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    ports:
      - "1602:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    networks:
      - rossmann-network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    ports:
      - "1603:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5

  jupyter-lab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter-lab
    networks:
      - rossmann-network
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8888:8888"
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    env_file:
      - .env